apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  name: aot-local
spec:
  storage:
    type: kine
    kine:
      dataSource: "sqlite:///var/lib/k0s/db/state.db"
  api:
    address: 127.0.0.1
    port: 6443
  network:
    provider: kube-router
    podCIDR: 10.244.0.0/16
    serviceCIDR: 10.96.0.0/12
