apiVersion: k0s.k0sproject.io/v1beta1
kind: ClusterConfig
metadata:
  name: aot-local
spec:
  storage:
    type: kine
    kine:
      dataSource: "sqlite:///var/lib/k0s/db/state.db"
  network:
    provider: kuberouter
    podCIDR: 10.244.0.0/16
    serviceCIDR: 10.96.0.0/12
    kubeRouter:
      metricsPort: 8181
