// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClusterStatus() {
  return window['go']['main']['App']['ClusterStatus']();
}

export function GetEnvVars() {
  return window['go']['main']['App']['GetEnvVars']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function HealthCheck() {
  return window['go']['main']['App']['HealthCheck']();
}

export function ListServices() {
  return window['go']['main']['App']['ListServices']();
}

export function OpenService(arg1) {
  return window['go']['main']['App']['OpenService'](arg1);
}

export function RestartService(arg1) {
  return window['go']['main']['App']['RestartService'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartCluster() {
  return window['go']['main']['App']['StartCluster']();
}

export function StartPortForward(arg1, arg2) {
  return window['go']['main']['App']['StartPortForward'](arg1, arg2);
}

export function StopCluster() {
  return window['go']['main']['App']['StopCluster']();
}

export function StopPortForward(arg1) {
  return window['go']['main']['App']['StopPortForward'](arg1);
}
