// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AutodetectNamespace(arg1:string):Promise<string>;

export function ClusterStatus():Promise<string>;

export function DisconnectGitHub():Promise<void>;

export function GetEnvVars():Promise<Array<main.EnvVarInfo>>;

export function GetGitHubUser():Promise<string>;

export function GetKubeContexts():Promise<Array<string>>;

export function GetSettings():Promise<main.AppSettings>;

export function HealthCheck():Promise<main.HealthReport>;

export function ListServices():Promise<Array<main.ServiceInfo>>;

export function OpenService(arg1:string):Promise<void>;

export function PollGitHubDeviceFlow(arg1:string):Promise<string>;

export function RestartService(arg1:string):Promise<void>;

export function SaveGitHubToken(arg1:string):Promise<void>;

export function SaveSettings(arg1:main.AppSettings):Promise<void>;

export function StartCluster():Promise<void>;

export function StartGitHubDeviceFlow():Promise<main.DeviceFlowStart>;

export function StartPortForward(arg1:string,arg2:number):Promise<void>;

export function StopCluster():Promise<void>;

export function StopPortForward(arg1:string):Promise<void>;
