// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function APIProxyMiddleware(arg1) {
  return window['go']['main']['App']['APIProxyMiddleware'](arg1);
}

export function AutodetectNamespace(arg1) {
  return window['go']['main']['App']['AutodetectNamespace'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function CheckLiteLLM(arg1) {
  return window['go']['main']['App']['CheckLiteLLM'](arg1);
}

export function ClusterStatus() {
  return window['go']['main']['App']['ClusterStatus']();
}

export function DisconnectGitHub() {
  return window['go']['main']['App']['DisconnectGitHub']();
}

export function GetEnvVars() {
  return window['go']['main']['App']['GetEnvVars']();
}

export function GetGitHubUser() {
  return window['go']['main']['App']['GetGitHubUser']();
}

export function GetKubeContexts() {
  return window['go']['main']['App']['GetKubeContexts']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function HealthCheck() {
  return window['go']['main']['App']['HealthCheck']();
}

export function ListServices() {
  return window['go']['main']['App']['ListServices']();
}

export function LogPath() {
  return window['go']['main']['App']['LogPath']();
}

export function OpenLogInConsole() {
  return window['go']['main']['App']['OpenLogInConsole']();
}

export function OpenService(arg1) {
  return window['go']['main']['App']['OpenService'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function PollGitHubDeviceFlow(arg1) {
  return window['go']['main']['App']['PollGitHubDeviceFlow'](arg1);
}

export function RestartService(arg1) {
  return window['go']['main']['App']['RestartService'](arg1);
}

export function SaveGitHubToken(arg1) {
  return window['go']['main']['App']['SaveGitHubToken'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartCluster() {
  return window['go']['main']['App']['StartCluster']();
}

export function StartGitHubDeviceFlow() {
  return window['go']['main']['App']['StartGitHubDeviceFlow']();
}

export function StartPortForward(arg1, arg2) {
  return window['go']['main']['App']['StartPortForward'](arg1, arg2);
}

export function StopCluster() {
  return window['go']['main']['App']['StopCluster']();
}

export function StopPortForward(arg1) {
  return window['go']['main']['App']['StopPortForward'](arg1);
}
